site_name: Railway Operation Simulator Package Manager
site_description: Documentation for Railway Operation Simulator Package Manager
site_author: Kristian Zarebski
site_url: https://railway-op-sim.github.io/RailOSPkgManager/
copyright: Â© Kristian Zarebski, 2022
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Creating Packages: creating_packages.md
  - Advanced Features: advanced.md
  - Upgrading ROS: upgrade.md
markdown_extensions:
  toc:
    permalink: true
  admonition: {}
  md_in_html: {}
  tables: {}
repo_name: GitHub
repo_url: https://github.com/Railway-Op-Sim/RailOSPkgManager
edit_uri: https://github.com/Railway-Op-Sim/RailOSPkgManager/edit/main/docs
theme:
  name: material
  logo: media/railospkgmanager_white.svg
  favicon: media/favicon.ico
  features:
    - toc.integrate
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
